services:
    db:
        image: postgres:18
        restart: unless-stopped
        environment:
            POSTGRES_USER: db
            POSTGRES_PASSWORD: db
            POSTGRES_DB: mathisi
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql
    valkey:
        image: valkey/valkey:latest
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./data/valkey:/data
