[general]
listen_address = [
    "0.0.0.0:8080",
    "[::]:8080",
]
public_url = "http://localhost:8080/"

[db]
connection_string = "postgres://db:db@localhost/mathisi"

[redis]
connection_string = "redis://localhost:6379"
